server:
  port: 8081

spring:
  messages:
    basename: messages
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  config:
    import: application-secret.yml

  mail:
    host: smtp.gmail.com
    port: 587
    username: yun986927@gmail.com
    password: ${spring.email.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

cloud:
  aws:
    s3:
      bucket: kcc-bucket
      url : https://kcc-bucket.s3.ap-northeast-2.amazonaws.com/
    credentials:
      access-key: ${cloud.aws.accessKey}
      secret-key: ${cloud.aws.secretKey}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:data-h2.sql

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:${ORACLE_PORT}:XE
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
  sql:
    init:
      mode: never



